name: Analyse
on: [push, pull_request]
jobs:
  test:
    name: (JDK ${{ matrix.jdk }} / ${{ matrix.os }}) Test
    env:
      MAVEN_OPTS: -XX:+IgnoreUnrecognizedVMOptions --illegal-access=warn
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        jdk: ['8']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK ${{ matrix.jdk }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.jdk }}
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Maven Test
        timeout-minutes: 40
        run: mvn -V -B -DtrimStackTrace=false clean verify
      - name: Archive build logs
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: build-logs
          path: |
            **/hs_err_pid*.log
            **/target/surefire-reports/*
